%% FIG_TRIADIC_REGULATION.M  -  Triadic regulation: concept + INC + DEC
%  Requires: results_triadic.mat (generated by precompute_fig_data.m)
%  Output:   ../Plots/fig_triadic_regulation.pdf/png

clc; clear; close all;

results_path = fullfile(fileparts(mfilename('fullpath')), 'results_triadic.mat');
if ~exist(results_path,'file')
    error('results_triadic.mat not found.');
end
load(results_path);

%% ---- Colour palette (Wong 2011, CBF-safe) --------------------------------
C.blue   = [0.000 0.447 0.698];
C.orange = [0.902 0.624 0.000];
C.red    = [0.835 0.369 0.000];
C.green  = [0.000 0.620 0.451];
C.grey   = [0.600 0.600 0.600];
C.black  = [0     0     0    ];

div_cm = interp1(linspace(0,1,5), ...
    [C.blue;[0.3,0.6,0.9];[0.97,0.97,0.97];[0.99,0.68,0.25];C.red], ...
    linspace(0,1,256));

set(0,'DefaultAxesFontName','Times New Roman','DefaultAxesFontSize',8, ...
      'DefaultTextFontName','Times New Roman');

fprintf('INC: Theta_Sigma = %.1f\nDEC: Theta_Sigma = %.1f\n',Theta_inc,Theta_dec);

%% Figure
fig = figure('Units','centimeters','Position',[2 4 16 4],'Color','w');
tl  = tiledlayout(1,3,'TileSpacing','compact','Padding','tight');

%% ---- (a) Schematic: triadic amplitude regulation ------------------------
ax_a = nexttile(tl,1);
set(ax_a,'Color','w','Box','off');
xlim([0 10]); ylim([0 11.5]);
hold on; axis off;

rn   = 1.0;
th_c = linspace(0,2*pi,80);
cx   = rn*cos(th_c);  cy = rn*sin(th_c);

% Node positions
xX=1.7; yX=2.8;   xY=8.3; yY=2.8;   xZ=5.0; yZ=8.8;

% --- X-Y coupling arrow (bidirectional, solid black) ---
x1 = xX+rn;  y1 = yX;
x2 = xY-rn;  y2 = yY;
plot([x1+0.2,x2-0.2],[y1,y2],'-','Color',C.black,'LineWidth',2.2);
tri_head(ax_a,[x1+0.3,y1],[x1,y1],C.black,0.24);   % arrowhead at X end
tri_head(ax_a,[x2-0.3,y2],[x2,y2],C.black,0.24);   % arrowhead at Y end

% --- Z -> midpoint of X-Y coupling (dashed green, regulation) ---
zx1=xZ; zy1=yZ-rn;   % bottom of Z node
zx2=xZ; zy2=yX+0.15; % just above coupling arrow
plot([zx1,zx2],[zy1,zy2],'--','Color',C.green,'LineWidth',1.9);
tri_head(ax_a,[zx1,zy1],[zx2,zy2],C.green,0.24);
text(xZ+0.30,(yZ+yX)/2+0.4,'regulates','HorizontalAlignment','left',...
    'Interpreter','none','FontSize',7.5,'Color',C.green,'FontWeight','bold');

% --- Filled nodes (drawn last so they cover arrow ends) ---
fill(xX+cx-0.1, yX+cy, C.blue,   'EdgeColor','w','LineWidth',1.5);
text(xX-0.05, yX,'$X$','HorizontalAlignment','center','Interpreter','latex',...
    'FontSize',9,'Color','w','FontWeight','bold');
text(xX, yX-rn-0.45-0.1,'$f_X$','HorizontalAlignment','center','Interpreter','latex',...
    'FontSize',7.5,'Color',C.blue);

fill(xY+cx+0.1, yY+cy, C.orange, 'EdgeColor','w','LineWidth',1.5);
text(xY+0.1, yY,'$Y$','HorizontalAlignment','center','Interpreter','latex',...
    'FontSize',9,'Color','w','FontWeight','bold');
text(xY, yY-rn-0.45-0.1,'$f_Y$','HorizontalAlignment','center','Interpreter','latex',...
    'FontSize',7.5,'Color',C.orange);

fill(xZ+cx, yZ+cy, C.green,  'EdgeColor','w','LineWidth',1.5);
text(xZ, yZ,'$Z$','HorizontalAlignment','center','Interpreter','latex',...
    'FontSize',9,'Color','w','FontWeight','bold');
text(xZ, yZ+rn+0.45+.1,'$f_Z$','HorizontalAlignment','center','Interpreter','latex',...
    'FontSize',7.5,'Color',C.green);

hold off;axis square;
title('(a) Amplitude regulation','Interpreter','Latex','FontSize',8.5);

%% ---- (b) INC fingerprint ------------------------------------------------
ax_b = nexttile(tl,2);
MI_dev_inc = MIz_inc - mean(MIz_inc);
clim_b = max(abs(MI_dev_inc))+eps;
fill([m_ax;flipud(m_ax)],[MI_lo_inc(:);flipud(MI_hi_inc(:))],C.grey,...
    'FaceAlpha',0.30,'EdgeColor','none'); hold on;
plot(m_ax,MI_mean_null_inc(:),'-','Color',C.grey,'LineWidth',0.9);
scatter(m_ax,MIz_inc,28,MI_dev_inc,'filled','MarkerFaceAlpha',0.85);
plot(m_ax,movmean(MIz_inc,max(3,floor(numel(m_ax)/6))),'-k','LineWidth',2.0);
yline(mean(MIz_inc),'--','Color',C.black,'LineWidth',0.8,'Alpha',0.4);
hold off;
colormap(ax_b,div_cm);
clim(ax_b,[-clim_b,clim_b]);
xlabel(ax_b,'Percentile of $|Z|$','Interpreter','latex');
ylabel(ax_b,'$\mathrm{MI}(X,Y\,|\,z_m)$','Interpreter','latex');
title(ax_b,'(b) INC: $Z$ amplifies $X$--$Y$ coupling','Interpreter','latex','FontSize',9);
text(ax_b,0.36,0.2,sprintf('$\\Theta_\\Sigma = %.1f$',Theta_inc),'Units','norm',...
    'Interpreter','latex','FontSize',8.5,'Color',C.green,'FontWeight','bold');
text(ax_b,0.36,0.10,'MI $\uparrow$ with $|Z|$','Units','norm','Interpreter','latex',...
    'FontSize',8,'Color',C.red,'HorizontalAlignment','left','FontWeight','bold');
box(ax_b,'on'); grid(ax_b,'on');

%% ---- (c) DEC fingerprint ------------------------------------------------
ax_c = nexttile(tl,3);
MI_dev_dec = MIz_dec - mean(MIz_dec);
clim_c = max(abs(MI_dev_dec))+eps;
fill([m_ax;flipud(m_ax)],[MI_lo_dec(:);flipud(MI_hi_dec(:))],C.grey,...
    'FaceAlpha',0.30,'EdgeColor','none'); hold on;
plot(m_ax,MI_mean_null_dec(:),'-','Color',C.grey,'LineWidth',0.9);
scatter(m_ax,MIz_dec,28,MI_dev_dec,'filled','MarkerFaceAlpha',0.85);
plot(m_ax,movmean(MIz_dec,max(3,floor(numel(m_ax)/6))),'-k','LineWidth',2.0);
yline(mean(MIz_dec),'--','Color',C.black,'LineWidth',0.8,'Alpha',0.4);
hold off;
colormap(ax_c,div_cm);
clim(ax_c,[-clim_c,clim_c]);
cb_b = colorbar(ax_c,'Location','eastoutside','FontSize',7);
xlabel(ax_c,'Percentile of $|Z|$','Interpreter','latex');
ylabel(ax_c,'$\mathrm{MI}(X,Y\,|\,z_m)$','Interpreter','latex');
title(ax_c,'(c) DEC: $Z$ suppresses $X$--$Y$ coupling','Interpreter','latex','FontSize',9);
text(ax_c,0.56,0.2,sprintf('$\\Theta_\\Sigma = %.1f$',Theta_dec),'Units','norm',...
    'Interpreter','latex','FontSize',8.5,'Color',C.green,'FontWeight','bold','HorizontalAlignment','right');
text(ax_c,0.56,0.10,'MI $\downarrow$ with $|Z|$','Units','norm','Interpreter','latex',...
    'FontSize',8,'Color',C.blue,'HorizontalAlignment','right','FontWeight','bold');
box(ax_c,'on'); grid(ax_c,'on');

%% ---- Save ----------------------------------------------------------------
out_dir = fullfile(fileparts(mfilename('fullpath')), '..', 'Plots');
if ~exist(out_dir,'dir'), mkdir(out_dir); end
print(fig, fullfile(out_dir,'fig_triadic_regulation.pdf'), '-dpdf', '-vector', '-r300');
print(fig, fullfile(out_dir,'fig_triadic_regulation.png'), '-dpng', '-r300');
fprintf('Saved: Plots/fig_triadic_regulation\n');

%% ---- Local helper --------------------------------------------------------
function tri_head(ax, p1, p2, clr, hw)
% Filled arrowhead from p1 toward p2, tip at p2.
    dx=p2(1)-p1(1); dy=p2(2)-p1(2); L=sqrt(dx^2+dy^2);
    if L<1e-9, return; end
    dn=[dx/L, dy/L]; hl=hw*1.5;
    tip  = p2;
    base = [p2(1)-hl*dn(1),      p2(2)-hl*dn(2)     ];
    lft  = [base(1)+hw*(-dn(2)),  base(2)+hw*( dn(1)) ];
    rgt  = [base(1)-hw*(-dn(2)),  base(2)-hw*( dn(1)) ];
    fill(ax,[tip(1),lft(1),rgt(1)],[tip(2),lft(2),rgt(2)],...
        clr,'EdgeColor',clr,'LineWidth',0.5);
end
